name: Bug Report
description: Create a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: checkboxes
    id: check
    attributes:
      label: Did You Cipher Through Other Issues?
      description: "Please check out other issues before continuing. I will close this issue if it's a duplicate."
      options:
      - label: "I have checked other issues"
        required: true
  - type: textarea
    id: bug-description
    attributes:
      label: "Describe The Bug In Detail"
      description: "Please describe the bug and make sure it's clear and concise."
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help give me a bigger picture of the issue at hand (It'll be very convenient and helpful if you do)."
      render: bash
  - type: textarea
    id: other
    attributes:
      label: "More the merrier"
  - type: dropdown
  id: Issue
  attributes:
    label: In your opinion, what would you say this issue falls under?
    options:
      - Bug
      - Odd
      - Idiot
  validations:
    required: true
