name: Channel Icon
description: Suggest a Channel Icon or fix.
title: "[Channel Icon]: "
assignees: misspent
labels: ["Channel Icon"]
body:
  - type: checkboxes
    id: check
    attributes:
      label: 🔍 Did you check former issues/requests?
      description: "Please check out other issues before continuing. I will close this issue if it's a duplicate."
      options:
      - label: "I have checked other issues"
        required: true
  - type: checkboxes
    id: check
    attributes:
      label: 🔍 Do you have the HTML path or link to a site?
      description: "HTML path = link/address"
      options:
      - label: "I have checked other issues"
        required: true
  - type: textarea
    id: icon-suggestion
    attributes:
      label: "📝 Describe what channel Icon you want added"
      description: "WWhere you got it from, what's the name of the channel and HTML path."
      value: |
        Site:
        Channel name: 
        HTML Path (optional):
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "📸 Screenshots/Icon(s)"
      description: "If applicable, add screenshots or Icon images here, this will make everything easier for you and me."
      render: bash
  - type: textarea
    id: other
    attributes:
      label: "➕ More the merrier"
      description: "Off topic, redundant or something you didn't want in the description"
